// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ5UIzqnhE1yWv3swgc-gOP50SPPhZsfk',
    appId: '1:783481758973:web:bd8f1581465045100a8a94',
    messagingSenderId: '783481758973',
    projectId: 'fir-miner-60b30',
    authDomain: 'fir-miner-60b30.firebaseapp.com',
    storageBucket: 'fir-miner-60b30.appspot.com',
    measurementId: 'G-PM57SP19DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fe-EQGKiExZTr4lpijJMyamXHzJnGjI',
    appId: '1:783481758973:android:85934d7f3210516a0a8a94',
    messagingSenderId: '783481758973',
    projectId: 'fir-miner-60b30',
    storageBucket: 'fir-miner-60b30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6rFqWWGwavVrW4iLit57hAgbBQXjUmM',
    appId: '1:783481758973:ios:ac7f5531423e03f30a8a94',
    messagingSenderId: '783481758973',
    projectId: 'fir-miner-60b30',
    storageBucket: 'fir-miner-60b30.appspot.com',
    iosBundleId: 'com.example.firebaseMiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp6rFqWWGwavVrW4iLit57hAgbBQXjUmM',
    appId: '1:783481758973:ios:ac7f5531423e03f30a8a94',
    messagingSenderId: '783481758973',
    projectId: 'fir-miner-60b30',
    storageBucket: 'fir-miner-60b30.appspot.com',
    iosBundleId: 'com.example.firebaseMiner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ5UIzqnhE1yWv3swgc-gOP50SPPhZsfk',
    appId: '1:783481758973:web:a8146bf97a6dc1480a8a94',
    messagingSenderId: '783481758973',
    projectId: 'fir-miner-60b30',
    authDomain: 'fir-miner-60b30.firebaseapp.com',
    storageBucket: 'fir-miner-60b30.appspot.com',
    measurementId: 'G-WKNJHM6CHY',
  );
}
